package com.slaviboy.flags

import androidx.annotation.DrawableRes
import androidx.annotation.StringRes

enum class Country(
    val code: String,
    val diallingCode: String,
    @StringRes val countryResId: Int,
    @DrawableRes val icon1x1ResId: Int,
    @DrawableRes val icon4x3ResId: Int
) {
    Afghanistan("af", "+93", R.string.afghanistan, R.drawable.ic_flag_1x1_af, R.drawable.ic_flag_4x3_af),
    Albania("al", "+355", R.string.albania, R.drawable.ic_flag_1x1_al, R.drawable.ic_flag_4x3_al),
    Algeria("dz", "+213", R.string.algeria, R.drawable.ic_flag_1x1_dz, R.drawable.ic_flag_4x3_dz),
    Andorra("ad", "+376", R.string.andorra, R.drawable.ic_flag_1x1_ad, R.drawable.ic_flag_4x3_ad),
    Angola("ao", "+244", R.string.angola, R.drawable.ic_flag_1x1_ao, R.drawable.ic_flag_4x3_ao),
    Argentina("ar", "+54", R.string.argentina, R.drawable.ic_flag_1x1_ar, R.drawable.ic_flag_4x3_ar),
    Armenia("am", "+374", R.string.armenia, R.drawable.ic_flag_1x1_am, R.drawable.ic_flag_4x3_am),
    Australia("au", "+61", R.string.australia, R.drawable.ic_flag_1x1_au, R.drawable.ic_flag_4x3_au),
    Austria("at", "+43", R.string.austria, R.drawable.ic_flag_1x1_at, R.drawable.ic_flag_4x3_at),
    Azerbaijan("az", "+994", R.string.azerbaijan, R.drawable.ic_flag_1x1_az, R.drawable.ic_flag_4x3_az),
    Bahamas("bs", "+1-242", R.string.bahamas, R.drawable.ic_flag_1x1_bs, R.drawable.ic_flag_4x3_bs),
    Bahrain("bh", "+973", R.string.bahrain, R.drawable.ic_flag_1x1_bh, R.drawable.ic_flag_4x3_bh),
    Bangladesh("bd", "+880", R.string.bangladesh, R.drawable.ic_flag_1x1_bd, R.drawable.ic_flag_4x3_bd),
    Barbados("bb", "+1-246", R.string.barbados, R.drawable.ic_flag_1x1_bb, R.drawable.ic_flag_4x3_bb),
    Belarus("by", "+375", R.string.belarus, R.drawable.ic_flag_1x1_by, R.drawable.ic_flag_4x3_by),
    Belgium("be", "+32", R.string.belgium, R.drawable.ic_flag_1x1_be, R.drawable.ic_flag_4x3_be),
    Belize("bz", "+501", R.string.belize, R.drawable.ic_flag_1x1_bz, R.drawable.ic_flag_4x3_bz),
    Benin("bj", "+229", R.string.benin, R.drawable.ic_flag_1x1_bj, R.drawable.ic_flag_4x3_bj),
    Bhutan("bt", "+975", R.string.bhutan, R.drawable.ic_flag_1x1_bt, R.drawable.ic_flag_4x3_bt),
    Bolivia("bo", "+591", R.string.bolivia, R.drawable.ic_flag_1x1_bo, R.drawable.ic_flag_4x3_bo),
    BosniaAndHerzegovina("ba", "+387", R.string.bosnia_and_herzegovina, R.drawable.ic_flag_1x1_ba, R.drawable.ic_flag_4x3_ba),
    Botswana("bw", "+267", R.string.botswana, R.drawable.ic_flag_1x1_bw, R.drawable.ic_flag_4x3_bw),
    Brazil("br", "+55", R.string.brazil, R.drawable.ic_flag_1x1_br, R.drawable.ic_flag_4x3_br),
    Brunei("bn", "+673", R.string.brunei, R.drawable.ic_flag_1x1_bn, R.drawable.ic_flag_4x3_bn),
    Bulgaria("bg", "+359", R.string.bulgaria, R.drawable.ic_flag_1x1_bg, R.drawable.ic_flag_4x3_bg),
    Burundi("bi", "+257", R.string.burundi, R.drawable.ic_flag_1x1_bi, R.drawable.ic_flag_4x3_bi),
    Cambodia("kh", "+855", R.string.cambodia, R.drawable.ic_flag_1x1_kh, R.drawable.ic_flag_4x3_kh),
    Cameroon("cm", "+237", R.string.cameroon, R.drawable.ic_flag_1x1_cm, R.drawable.ic_flag_4x3_cm),
    Canada("ca", "+1", R.string.canada, R.drawable.ic_flag_1x1_ca, R.drawable.ic_flag_4x3_ca),
    CapeVerde("cv", "+238", R.string.cape_verde, R.drawable.ic_flag_1x1_cv, R.drawable.ic_flag_4x3_cv),
    CentralAfricanRepublic("cf", "+236", R.string.central_african_rep, R.drawable.ic_flag_1x1_cf, R.drawable.ic_flag_4x3_cf),
    Chad("td", "+235", R.string.chad, R.drawable.ic_flag_1x1_td, R.drawable.ic_flag_4x3_td),
    Chile("cl", "+56", R.string.chile, R.drawable.ic_flag_1x1_cl, R.drawable.ic_flag_4x3_cl),
    China("cn", "+86", R.string.china, R.drawable.ic_flag_1x1_cn, R.drawable.ic_flag_4x3_cn),
    Colombia("co", "+57", R.string.colombia, R.drawable.ic_flag_1x1_co, R.drawable.ic_flag_4x3_co),
    Comoros("km", "+269", R.string.comoros, R.drawable.ic_flag_1x1_km, R.drawable.ic_flag_4x3_km),
    RepublicOfTheCongo("cg", "+242", R.string.republic_of_congo, R.drawable.ic_flag_1x1_cg, R.drawable.ic_flag_4x3_cg),
    CostaRica("cr", "+506", R.string.costa_rica, R.drawable.ic_flag_1x1_cr, R.drawable.ic_flag_4x3_cr),
    Croatia("hr", "+385", R.string.croatia, R.drawable.ic_flag_1x1_hr, R.drawable.ic_flag_4x3_hr),
    Cuba("cu", "+53", R.string.cuba, R.drawable.ic_flag_1x1_cu, R.drawable.ic_flag_4x3_cu),
    Cyprus("cy", "+357", R.string.cyprus, R.drawable.ic_flag_1x1_cy, R.drawable.ic_flag_4x3_cy),
    CzechRepublic("cz", "+420", R.string.czech_republic, R.drawable.ic_flag_1x1_cz, R.drawable.ic_flag_4x3_cz),
    Denmark("dk", "+45", R.string.denmark, R.drawable.ic_flag_1x1_dk, R.drawable.ic_flag_4x3_dk),
    Djibouti("dj", "+253", R.string.djibouti, R.drawable.ic_flag_1x1_dj, R.drawable.ic_flag_4x3_dj),
    Dominica("dm", "+1-767", R.string.dominica, R.drawable.ic_flag_1x1_dm, R.drawable.ic_flag_4x3_dm),
    DominicanRepublic("do", "+1-809", R.string.dominican_republic, R.drawable.ic_flag_1x1_do, R.drawable.ic_flag_4x3_do),
    EastTimor("tl", "+670", R.string.east_timor, R.drawable.ic_flag_1x1_tl, R.drawable.ic_flag_4x3_tl),
    Ecuador("ec", "+593", R.string.ecuador, R.drawable.ic_flag_1x1_ec, R.drawable.ic_flag_4x3_ec),
    Egypt("eg", "+20", R.string.egypt, R.drawable.ic_flag_1x1_eg, R.drawable.ic_flag_4x3_eg),
    ElSalvador("sv", "+503", R.string.el_salvador, R.drawable.ic_flag_1x1_sv, R.drawable.ic_flag_4x3_sv),
    EquatorialGuinea("gq", "+240", R.string.equatorial_guinea, R.drawable.ic_flag_1x1_gq, R.drawable.ic_flag_4x3_gq),
    Eritrea("er", "+291", R.string.eritrea, R.drawable.ic_flag_1x1_er, R.drawable.ic_flag_4x3_er),
    Estonia("ee", "+372", R.string.estonia, R.drawable.ic_flag_1x1_ee, R.drawable.ic_flag_4x3_ee),
    Ethiopia("et", "+251", R.string.ethiopia, R.drawable.ic_flag_1x1_et, R.drawable.ic_flag_4x3_et),
    Fiji("fj", "+679", R.string.fiji, R.drawable.ic_flag_1x1_fj, R.drawable.ic_flag_4x3_fj),
    Finland("fi", "+358", R.string.finland, R.drawable.ic_flag_1x1_fi, R.drawable.ic_flag_4x3_fi),
    France("fr", "+33", R.string.france, R.drawable.ic_flag_1x1_fr, R.drawable.ic_flag_4x3_fr),
    Gabon("ga", "+241", R.string.gabon, R.drawable.ic_flag_1x1_ga, R.drawable.ic_flag_4x3_ga),
    Gambia("gm", "+220", R.string.gambia, R.drawable.ic_flag_1x1_gm, R.drawable.ic_flag_4x3_gm),
    Georgia("ge", "+995", R.string.georgia, R.drawable.ic_flag_1x1_ge, R.drawable.ic_flag_4x3_ge),
    Germany("de", "+49", R.string.germany, R.drawable.ic_flag_1x1_de, R.drawable.ic_flag_4x3_de),
    Ghana("gh", "+233", R.string.ghana, R.drawable.ic_flag_1x1_gh, R.drawable.ic_flag_4x3_gh),
    Greece("gr", "+30", R.string.greece, R.drawable.ic_flag_1x1_gr, R.drawable.ic_flag_4x3_gr),
    Grenada("gd", "+1-473", R.string.grenada, R.drawable.ic_flag_1x1_gd, R.drawable.ic_flag_4x3_gd),
    Guatemala("gt", "+502", R.string.guatemala, R.drawable.ic_flag_1x1_gt, R.drawable.ic_flag_4x3_gt),
    Guinea("gn", "+224", R.string.guinea, R.drawable.ic_flag_1x1_gn, R.drawable.ic_flag_4x3_gn),
    GuineaBissau("gw", "+245", R.string.guinea_bissau, R.drawable.ic_flag_1x1_gw, R.drawable.ic_flag_4x3_gw),
    Guyana("gy", "+592", R.string.guyana, R.drawable.ic_flag_1x1_gy, R.drawable.ic_flag_4x3_gy),
    Haiti("ht", "+509", R.string.haiti, R.drawable.ic_flag_1x1_ht, R.drawable.ic_flag_4x3_ht),
    Honduras("hn", "+504", R.string.honduras, R.drawable.ic_flag_1x1_hn, R.drawable.ic_flag_4x3_hn),
    Hungary("hu", "+36", R.string.hungary, R.drawable.ic_flag_1x1_hu, R.drawable.ic_flag_4x3_hu),
    Iceland("is", "+354", R.string.iceland, R.drawable.ic_flag_1x1_is, R.drawable.ic_flag_4x3_is),
    India("in", "+91", R.string.india, R.drawable.ic_flag_1x1_in, R.drawable.ic_flag_4x3_in),
    Indonesia("id", "+62", R.string.indonesia, R.drawable.ic_flag_1x1_id, R.drawable.ic_flag_4x3_id),
    Iran("ir", "+98", R.string.iran, R.drawable.ic_flag_1x1_ir, R.drawable.ic_flag_4x3_ir),
    Iraq("iq", "+964", R.string.iraq, R.drawable.ic_flag_1x1_iq, R.drawable.ic_flag_4x3_iq),
    Ireland("ie", "+353", R.string.ireland, R.drawable.ic_flag_1x1_ie, R.drawable.ic_flag_4x3_ie),
    Israel("il", "+972", R.string.israel, R.drawable.ic_flag_1x1_il, R.drawable.ic_flag_4x3_il),
    Italy("it", "+39", R.string.italy, R.drawable.ic_flag_1x1_it, R.drawable.ic_flag_4x3_it),
    IvoryCoast("ci", "+225", R.string.ivory_coast, R.drawable.ic_flag_1x1_ci, R.drawable.ic_flag_4x3_ci),
    Jamaica("jm", "+1-876", R.string.jamaica, R.drawable.ic_flag_1x1_jm, R.drawable.ic_flag_4x3_jm),
    Japan("jp", "+81", R.string.japan, R.drawable.ic_flag_1x1_jp, R.drawable.ic_flag_4x3_jp),
    Jordan("jo", "+962", R.string.jordan, R.drawable.ic_flag_1x1_jo, R.drawable.ic_flag_4x3_jo),
    Kazakhstan("kz", "+7", R.string.kazakhstan, R.drawable.ic_flag_1x1_kz, R.drawable.ic_flag_4x3_kz),
    Kenya("ke", "+254", R.string.kenya, R.drawable.ic_flag_1x1_ke, R.drawable.ic_flag_4x3_ke),
    Kiribati("ki", "+686", R.string.kiribati, R.drawable.ic_flag_1x1_ki, R.drawable.ic_flag_4x3_ki),
    NorthKorea("kp", "+850", R.string.north_korea, R.drawable.ic_flag_1x1_kp, R.drawable.ic_flag_4x3_kp),
    SouthKorea("kr", "+82", R.string.south_korea, R.drawable.ic_flag_1x1_kr, R.drawable.ic_flag_4x3_kr),
    Kosovo("xk", "+383", R.string.kosovo, R.drawable.ic_flag_1x1_xk, R.drawable.ic_flag_4x3_xk),
    Kuwait("kw", "+965", R.string.kuwait, R.drawable.ic_flag_1x1_kw, R.drawable.ic_flag_4x3_kw),
    Kyrgyzstan("kg", "+996", R.string.kyrgyzstan, R.drawable.ic_flag_1x1_kg, R.drawable.ic_flag_4x3_kg),
    Laos("la", "+856", R.string.laos, R.drawable.ic_flag_1x1_la, R.drawable.ic_flag_4x3_la),
    Latvia("lv", "+371", R.string.latvia, R.drawable.ic_flag_1x1_lv, R.drawable.ic_flag_4x3_lv),
    Lebanon("lb", "+961", R.string.lebanon, R.drawable.ic_flag_1x1_lb, R.drawable.ic_flag_4x3_lb),
    Lesotho("ls", "+266", R.string.lesotho, R.drawable.ic_flag_1x1_ls, R.drawable.ic_flag_4x3_ls),
    Liberia("lr", "+231", R.string.liberia, R.drawable.ic_flag_1x1_lr, R.drawable.ic_flag_4x3_lr),
    Libya("ly", "+218", R.string.libya, R.drawable.ic_flag_1x1_ly, R.drawable.ic_flag_4x3_ly),
    Liechtenstein("li", "+423", R.string.liechtenstein, R.drawable.ic_flag_1x1_li, R.drawable.ic_flag_4x3_li),
    Lithuania("lt", "+370", R.string.lithuania, R.drawable.ic_flag_1x1_lt, R.drawable.ic_flag_4x3_lt),
    Luxembourg("lu", "+352", R.string.luxembourg, R.drawable.ic_flag_1x1_lu, R.drawable.ic_flag_4x3_lu),
    Macedonia("mk", "+389", R.string.macedonia, R.drawable.ic_flag_1x1_mk, R.drawable.ic_flag_4x3_mk),
    Madagascar("mg", "+261", R.string.madagascar, R.drawable.ic_flag_1x1_mg, R.drawable.ic_flag_4x3_mg),
    Malawi("mw", "+265", R.string.malawi, R.drawable.ic_flag_1x1_mw, R.drawable.ic_flag_4x3_mw),
    Malaysia("my", "+60", R.string.malaysia, R.drawable.ic_flag_1x1_my, R.drawable.ic_flag_4x3_my),
    Maldives("mv", "+960", R.string.maldives, R.drawable.ic_flag_1x1_mv, R.drawable.ic_flag_4x3_mv),
    Mali("ml", "+223", R.string.mali, R.drawable.ic_flag_1x1_ml, R.drawable.ic_flag_4x3_ml),
    Malta("mt", "+356", R.string.malta, R.drawable.ic_flag_1x1_mt, R.drawable.ic_flag_4x3_mt),
    MarshallIslands("mh", "+692", R.string.marshall_islands, R.drawable.ic_flag_1x1_mh, R.drawable.ic_flag_4x3_mh),
    Mauritania("mr", "+222", R.string.mauritania, R.drawable.ic_flag_1x1_mr, R.drawable.ic_flag_4x3_mr),
    Mauritius("mu", "+230", R.string.mauritius, R.drawable.ic_flag_1x1_mu, R.drawable.ic_flag_4x3_mu),
    Mexico("mx", "+52", R.string.mexico, R.drawable.ic_flag_1x1_mx, R.drawable.ic_flag_4x3_mx),
    Micronesia("fm", "+691", R.string.micronesia, R.drawable.ic_flag_1x1_fm, R.drawable.ic_flag_4x3_fm),
    Moldova("md", "+373", R.string.moldova, R.drawable.ic_flag_1x1_md, R.drawable.ic_flag_4x3_md),
    Monaco("mc", "+377", R.string.monaco, R.drawable.ic_flag_1x1_mc, R.drawable.ic_flag_4x3_mc),
    Mongolia("mn", "+976", R.string.mongolia, R.drawable.ic_flag_1x1_mn, R.drawable.ic_flag_4x3_mn),
    Montenegro("me", "+382", R.string.montenegro, R.drawable.ic_flag_1x1_me, R.drawable.ic_flag_4x3_me),
    Morocco("ma", "+212", R.string.morocco, R.drawable.ic_flag_1x1_ma, R.drawable.ic_flag_4x3_ma),
    Mozambique("mz", "+258", R.string.mozambique, R.drawable.ic_flag_1x1_mz, R.drawable.ic_flag_4x3_mz),
    Myanmar("mm", "+95", R.string.myanmar, R.drawable.ic_flag_1x1_mm, R.drawable.ic_flag_4x3_mm),
    Namibia("na", "+264", R.string.namibia, R.drawable.ic_flag_1x1_na, R.drawable.ic_flag_4x3_na),
    Nauru("nr", "+674", R.string.nauru, R.drawable.ic_flag_1x1_nr, R.drawable.ic_flag_4x3_nr),
    Nepal("np", "+977", R.string.nepal, R.drawable.ic_flag_1x1_np, R.drawable.ic_flag_4x3_np),
    Netherlands("nl", "+31", R.string.netherlands, R.drawable.ic_flag_1x1_nl, R.drawable.ic_flag_4x3_nl),
    NewZealand("nz", "+64", R.string.new_zealand, R.drawable.ic_flag_1x1_nz, R.drawable.ic_flag_4x3_nz),
    Nicaragua("ni", "+505", R.string.nicaragua, R.drawable.ic_flag_1x1_ni, R.drawable.ic_flag_4x3_ni),
    Niger("ne", "+227", R.string.niger, R.drawable.ic_flag_1x1_ne, R.drawable.ic_flag_4x3_ne),
    Nigeria("ng", "+234", R.string.nigeria, R.drawable.ic_flag_1x1_ng, R.drawable.ic_flag_4x3_ng),
    Norway("no", "+47", R.string.norway, R.drawable.ic_flag_1x1_no, R.drawable.ic_flag_4x3_no),
    Oman("om", "+968", R.string.oman, R.drawable.ic_flag_1x1_om, R.drawable.ic_flag_4x3_om),
    Pakistan("pk", "+92", R.string.pakistan, R.drawable.ic_flag_1x1_pk, R.drawable.ic_flag_4x3_pk),
    Palau("pw", "+680", R.string.palau, R.drawable.ic_flag_1x1_pw, R.drawable.ic_flag_4x3_pw),
    Panama("pa", "+507", R.string.panama, R.drawable.ic_flag_1x1_pa, R.drawable.ic_flag_4x3_pa),
    PapuaNewGuinea("gp", "+675", R.string.papua_new_guinea, R.drawable.ic_flag_1x1_pg, R.drawable.ic_flag_4x3_pg),
    Paraguay("py", "+595", R.string.paraguay, R.drawable.ic_flag_1x1_py, R.drawable.ic_flag_4x3_py),
    Peru("pe", "+51", R.string.peru, R.drawable.ic_flag_1x1_pe, R.drawable.ic_flag_4x3_pe),
    Philippines("ph", "+63", R.string.philippines, R.drawable.ic_flag_1x1_ph, R.drawable.ic_flag_4x3_ph),
    Poland("pl", "+48", R.string.poland, R.drawable.ic_flag_1x1_pl, R.drawable.ic_flag_4x3_pl),
    Portugal("pt", "+351", R.string.portugal, R.drawable.ic_flag_1x1_pt, R.drawable.ic_flag_4x3_pt),
    Qatar("qa", "+974", R.string.qatar, R.drawable.ic_flag_1x1_qa, R.drawable.ic_flag_4x3_qa),
    Romania("ro", "+40", R.string.romania, R.drawable.ic_flag_1x1_ro, R.drawable.ic_flag_4x3_ro),
    Russia("ru", "+7", R.string.russia, R.drawable.ic_flag_1x1_ru, R.drawable.ic_flag_4x3_ru),
    Rwanda("rw", "+250", R.string.rwanda, R.drawable.ic_flag_1x1_rw, R.drawable.ic_flag_4x3_rw),
    StKittsAndNevis("kn", "+1-869", R.string.st_kitts_and_nevis, R.drawable.ic_flag_1x1_kn, R.drawable.ic_flag_4x3_kn),
    StLucia("lc", "+1-758", R.string.st_lucia, R.drawable.ic_flag_1x1_lc, R.drawable.ic_flag_4x3_lc),
    SaintVincentAndTheGrenadines("vc", "+1-784", R.string.saint_vincent_and_the_grenadines, R.drawable.ic_flag_1x1_vc, R.drawable.ic_flag_4x3_vc),
    Samoa("ws", "+685", R.string.samoa, R.drawable.ic_flag_1x1_ws, R.drawable.ic_flag_4x3_ws),
    SanMarino("sm", "+378", R.string.san_marino, R.drawable.ic_flag_1x1_sm, R.drawable.ic_flag_4x3_sm),
    SaoTomeAndPrincipe("st", "+239", R.string.sao_tome_and_principe, R.drawable.ic_flag_1x1_st, R.drawable.ic_flag_4x3_st),
    SaudiArabia("sa", "+966", R.string.saudi_arabia, R.drawable.ic_flag_1x1_sa, R.drawable.ic_flag_4x3_sa),
    Senegal("sn", "+221", R.string.senegal, R.drawable.ic_flag_1x1_sn, R.drawable.ic_flag_4x3_sn),
    Serbia("rs", "+381", R.string.serbia, R.drawable.ic_flag_1x1_rs, R.drawable.ic_flag_4x3_rs),
    Seychelles("sc", "+248", R.string.seychelles, R.drawable.ic_flag_1x1_sc, R.drawable.ic_flag_4x3_sc),
    SierraLeone("sl", "+232", R.string.sierra_leone, R.drawable.ic_flag_1x1_sl, R.drawable.ic_flag_4x3_sl),
    Singapore("sg", "+65", R.string.singapore, R.drawable.ic_flag_1x1_sg, R.drawable.ic_flag_4x3_sg),
    Slovakia("sk", "+421", R.string.slovakia, R.drawable.ic_flag_1x1_sk, R.drawable.ic_flag_4x3_sk),
    Slovenia("si", "+386", R.string.slovenia, R.drawable.ic_flag_1x1_si, R.drawable.ic_flag_4x3_si),
    SolomonIslands("sb", "+677", R.string.solomon_islands, R.drawable.ic_flag_1x1_sb, R.drawable.ic_flag_4x3_sb),
    Somalia("so", "+252", R.string.somalia, R.drawable.ic_flag_1x1_so, R.drawable.ic_flag_4x3_so),
    SouthAfrica("za", "+27", R.string.south_africa, R.drawable.ic_flag_1x1_za, R.drawable.ic_flag_4x3_za),
    SouthSudan("ss", "+211", R.string.south_sudan, R.drawable.ic_flag_1x1_ss, R.drawable.ic_flag_4x3_ss),
    Spain("es", "+34", R.string.spain, R.drawable.ic_flag_1x1_es, R.drawable.ic_flag_4x3_es),
    SriLanka("lk", "+94", R.string.sri_lanka, R.drawable.ic_flag_1x1_lk, R.drawable.ic_flag_4x3_lk),
    Sudan("sd", "+249", R.string.sudan, R.drawable.ic_flag_1x1_sd, R.drawable.ic_flag_4x3_sd),
    Suriname("sr", "+597", R.string.suriname, R.drawable.ic_flag_1x1_sr, R.drawable.ic_flag_4x3_sr),
    Swaziland("ss", "+268", R.string.swaziland, R.drawable.ic_flag_1x1_sz, R.drawable.ic_flag_4x3_sz),
    Sweden("se", "+46", R.string.sweden, R.drawable.ic_flag_1x1_se, R.drawable.ic_flag_4x3_se),
    Switzerland("ch", "+41", R.string.switzerland, R.drawable.ic_flag_1x1_ch, R.drawable.ic_flag_4x3_ch),
    Syria("sy", "+963", R.string.syria, R.drawable.ic_flag_1x1_sy, R.drawable.ic_flag_4x3_sy),
    Taiwan("tw", "+886", R.string.taiwan, R.drawable.ic_flag_1x1_tw, R.drawable.ic_flag_4x3_tw),
    Tajikistan("tj", "+992", R.string.tajikistan, R.drawable.ic_flag_1x1_tj, R.drawable.ic_flag_4x3_tj),
    Tanzania("tz", "+255", R.string.tanzania, R.drawable.ic_flag_1x1_tz, R.drawable.ic_flag_4x3_tz),
    Thailand("th", "+66", R.string.thailand, R.drawable.ic_flag_1x1_th, R.drawable.ic_flag_4x3_th),
    Togo("tg", "+228", R.string.togo, R.drawable.ic_flag_1x1_tg, R.drawable.ic_flag_4x3_tg),
    Tonga("to", "+676", R.string.tonga, R.drawable.ic_flag_1x1_to, R.drawable.ic_flag_4x3_to),
    TrinidadAndTobago("tt", "+1-868", R.string.trinidad_and_tobago, R.drawable.ic_flag_1x1_tt, R.drawable.ic_flag_4x3_tt),
    Tunisia("tn", "+216", R.string.tunisia, R.drawable.ic_flag_1x1_tn, R.drawable.ic_flag_4x3_tn),
    Turkey("tr", "+90", R.string.turkey, R.drawable.ic_flag_1x1_tr, R.drawable.ic_flag_4x3_tr),
    Turkmenistan("tm", "+993", R.string.turkmenistan, R.drawable.ic_flag_1x1_tm, R.drawable.ic_flag_4x3_tm),
    Tuvalu("tv", "+688", R.string.tuvalu, R.drawable.ic_flag_1x1_tv, R.drawable.ic_flag_4x3_tv),
    Uganda("ug", "+256", R.string.uganda, R.drawable.ic_flag_1x1_ug, R.drawable.ic_flag_4x3_ug),
    Ukraine("ua", "+380", R.string.ukraine, R.drawable.ic_flag_1x1_ua, R.drawable.ic_flag_4x3_ua),
    UnitedArabEmirates("ae", "+971", R.string.united_arab_emirates, R.drawable.ic_flag_1x1_ae, R.drawable.ic_flag_4x3_ae),
    UnitedKingdom("gb", "+44", R.string.united_kingdom, R.drawable.ic_flag_1x1_gb, R.drawable.ic_flag_4x3_gb),
    UnitedStates("us", "+1", R.string.united_states, R.drawable.ic_flag_1x1_us, R.drawable.ic_flag_4x3_us),
    Uruguay("uy", "+598", R.string.uruguay, R.drawable.ic_flag_1x1_uy, R.drawable.ic_flag_4x3_uy),
    Uzbekistan("uz", "+998", R.string.uzbekistan, R.drawable.ic_flag_1x1_uz, R.drawable.ic_flag_4x3_uz),
    Vanuatu("vu", "+678", R.string.vanuatu, R.drawable.ic_flag_1x1_vu, R.drawable.ic_flag_4x3_vu),
    VaticanCity("va", "+379", R.string.vatican_city, R.drawable.ic_flag_1x1_va, R.drawable.ic_flag_4x3_va),
    Venezuela("ve", "+58", R.string.venezuela, R.drawable.ic_flag_1x1_ve, R.drawable.ic_flag_4x3_ve),
    Vietnam("vn", "+84", R.string.vietnam, R.drawable.ic_flag_1x1_vn, R.drawable.ic_flag_4x3_vn),
    Yemen("ye", "+967", R.string.yemen, R.drawable.ic_flag_1x1_ye, R.drawable.ic_flag_4x3_ye),
    Zambia("zm", "+260", R.string.zambia, R.drawable.ic_flag_1x1_zm, R.drawable.ic_flag_4x3_zm),
    Zimbabwe("zw", "+263", R.string.zimbabwe, R.drawable.ic_flag_1x1_zw, R.drawable.ic_flag_4x3_zw);

    companion object {

        fun ofCountryCode(countryCode: String): Country? {
            return Country.values().firstOrNull {
                it.code == countryCode
            }
        }

        fun ofDialingCode(diallingCode: String): Country? {
            return Country.values().firstOrNull {
                it.diallingCode == diallingCode
            }
        }
    }
}